#!/usr/bin/env python3

import argparse
import json
import re
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RULES = ROOT / 'audit' / 'plex_coupling_rules.json'


def load_rules(path=DEFAULT_RULES):
    with path.open(encoding='utf-8') as handle:
        config = json.load(handle)
    config['_search'] = re.compile(config['search_pattern'], re.IGNORECASE)
    for rule in config['rules']:
        rule['_pattern'] = re.compile(rule['pattern'], re.IGNORECASE)
        rule['_path_pattern'] = re.compile(rule['path_pattern']) if rule.get('path_pattern') else None
    return config


def iter_source_files(root, config):
    extensions = set(config['included_extensions'])
    excluded = set(config['excluded_directories'])
    excluded_files = set(config.get('excluded_files', ()))
    for path in sorted(root.rglob('*')):
        relative = path.relative_to(root)
        relative_name = relative.as_posix()
        if (not path.is_file() or relative_name in excluded_files or
                any(part in excluded for part in relative.parts)):
            continue
        if path.suffix.lower() in extensions:
            yield path, relative_name


def classify(relative_path, line, config):
    for rule in config['rules']:
        if rule['_path_pattern'] and not rule['_path_pattern'].search(relative_path):
            continue
        if rule['_pattern'].search(line):
            return rule['category']
    return None


def audit(root=ROOT, rules_path=DEFAULT_RULES):
    config = load_rules(rules_path)
    matches = []
    for path, relative in iter_source_files(root, config):
        try:
            lines = path.read_text(encoding='utf-8').splitlines()
        except UnicodeDecodeError:
            continue
        for line_number, line in enumerate(lines, 1):
            if config['_search'].search(line):
                matches.append({
                    'path': relative,
                    'line': line_number,
                    'category': classify(relative, line, config),
                    'text': line.strip()[:240],
                })
    return matches


def render_markdown(matches):
    counts = Counter(match['category'] or 'UNCLASSIFIED' for match in matches)
    lines = [
        '# Plex Coupling Inventory', '',
        'Generated by `scripts/audit_plex_coupling.py` from `audit/plex_coupling_rules.json`.', '',
        '## Summary', '',
        '| Classification | Matching lines |', '|---|---:|',
    ]
    lines.extend('| {} | {} |'.format(category, count) for category, count in sorted(counts.items()))
    lines.extend(['', '## Files by classification', ''])
    for category in sorted(counts):
        files = sorted({match['path'] for match in matches if (match['category'] or 'UNCLASSIFIED') == category})
        lines.extend(['### {}'.format(category), '', *('- `{}`'.format(path) for path in files), ''])
    return '\n'.join(lines).rstrip() + '\n'


def main():
    parser = argparse.ArgumentParser(description='Classify Plex coupling in repository text sources.')
    parser.add_argument('--format', choices=('json', 'markdown'), default='markdown')
    parser.add_argument('--check', action='store_true', help='Fail if a matching line is unclassified.')
    args = parser.parse_args()
    matches = audit()
    unclassified = [match for match in matches if match['category'] is None]
    print(json.dumps(matches, indent=2) if args.format == 'json' else render_markdown(matches), end='')
    if args.check and unclassified:
        raise SystemExit('Found {} unclassified Plex coupling lines'.format(len(unclassified)))


if __name__ == '__main__':
    main()
